name: Build
on: [push]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Install dotnet tools
      run: dotnet tool restore
      
    - name: Build
      run: dotnet build transport/transport
      
    - name: Build2
      run: dotnet build transport/NunitMain

    - name: Test
      run: dotnet test transport/NunitMain
      
    - name: Test2
      run: dotnet  cake --target=Test --test-run-name=Windows --configuration=Release
      
    - name: Package
      run: dotnet cake --target=Package

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: package

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: Test results (Windows)
        path: test-results
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}\


